### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by MarkTsy** [niemingzhao/niemingzhao.github.io#1]
点开文章界面之后 就是一个 黑方快 看不到文章内容
---
thumbnail: false  # Custom page header image.
author: xxx  # Author.
categories:  # Categories.
- xxx
tags:  # Tags.
- xxx
qrcode: false  # Disable article qrcode.
share_menu: false  # Disable article share menu.
license: xxx  # License description of the article.
donate: false  # Disable article donate link.
toc: true  # Enable article toc.
comments: true  # Enable article comment.

tagcloud: true  # Turn the current page into a tagcloud page.
photos: # Turn the current page into a gallery page.
- xxx
title: Hello World
---
这个配置的问题吗

**Comment by niemingzhao** [comment]
可否上传下文章界面和文章front-matter的截图？
