### ISSUE TITLE
网页技术问题

### ISSUE THREAD

**Issue by chenxuhan615** [niemingzhao/niemingzhao.github.io#20]
文章的封面图怎么固定呢？每次更新网页都会随机一张。

**Comment by niemingzhao** [comment]
在md文件的front-matter中设置thumbnail属性

**Comment by chenxuhan615** [comment]
特别感谢您的回复，封面问题已解决！
另外还想请教一下 “关于”，“时间轴”或“相册”这些栏目中我创建好md文件
比如： cat “# test”>about/index.md 
但是点进去后没有网页的主题了，应该怎么弄？
